In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
b = np.array([1, 2, 'a'])

In [5]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
zero_array = np.zeros((2, 2))

In [8]:
zero_array

array([[0., 0.],
       [0., 0.]])

In [9]:
one_array = np.ones((2, 2, 3), dtype=int)

In [10]:
one_array

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [11]:
rand_array = np.random.rand(2, 3)

In [12]:
rand_array

array([[0.63470948, 0.91714438, 0.45377596],
       [0.39730405, 0.01190645, 0.95071348]])

In [13]:
a = np.array([1, 2, 3])

In [14]:
a[0]

1

In [15]:
a[1]

2

In [16]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [17]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
b[1, 1]

5

In [19]:
a = np.random.rand(2, 3, 4)

In [20]:
a

array([[[0.28840238, 0.47101532, 0.8728854 , 0.12292859],
        [0.94678379, 0.63188639, 0.80169573, 0.61604498],
        [0.46921257, 0.36118038, 0.64352999, 0.80273363]],

       [[0.16295407, 0.22851147, 0.01195493, 0.9198899 ],
        [0.97182967, 0.37502887, 0.43531711, 0.94097046],
        [0.50475502, 0.09861217, 0.74881383, 0.91929007]]])

In [21]:
a[1, 0:2, 1:]

array([[0.22851147, 0.01195493, 0.9198899 ],
       [0.37502887, 0.43531711, 0.94097046]])

In [22]:
a

array([[[0.28840238, 0.47101532, 0.8728854 , 0.12292859],
        [0.94678379, 0.63188639, 0.80169573, 0.61604498],
        [0.46921257, 0.36118038, 0.64352999, 0.80273363]],

       [[0.16295407, 0.22851147, 0.01195493, 0.9198899 ],
        [0.97182967, 0.37502887, 0.43531711, 0.94097046],
        [0.50475502, 0.09861217, 0.74881383, 0.91929007]]])

In [23]:
a.shape

(2, 3, 4)

In [24]:
np.reshape(a, (3, 2, 4))

array([[[0.28840238, 0.47101532, 0.8728854 , 0.12292859],
        [0.94678379, 0.63188639, 0.80169573, 0.61604498]],

       [[0.46921257, 0.36118038, 0.64352999, 0.80273363],
        [0.16295407, 0.22851147, 0.01195493, 0.9198899 ]],

       [[0.97182967, 0.37502887, 0.43531711, 0.94097046],
        [0.50475502, 0.09861217, 0.74881383, 0.91929007]]])

In [26]:
# np.reshape(a, (3, 3, 3))

In [27]:
a.T

array([[[0.28840238, 0.16295407],
        [0.94678379, 0.97182967],
        [0.46921257, 0.50475502]],

       [[0.47101532, 0.22851147],
        [0.63188639, 0.37502887],
        [0.36118038, 0.09861217]],

       [[0.8728854 , 0.01195493],
        [0.80169573, 0.43531711],
        [0.64352999, 0.74881383]],

       [[0.12292859, 0.9198899 ],
        [0.61604498, 0.94097046],
        [0.80273363, 0.91929007]]])

In [28]:
import numpy as np

In [29]:
from timeit import Timer

In [30]:
my_list = list(range(10 ** 6))

In [31]:
my_array = np.array(my_list)

In [32]:
def for_add():
    return [item + 1 for item in my_list]

In [33]:
def vec_add():
    return my_array + 1

In [34]:
print('For-loop addition:')
print(min(Timer(for_add).repeat(10, 10)))

For-loop addition:
0.5027269000001979


In [35]:
print('Vectorized addition:')
print(min(Timer(vec_add).repeat(10, 10)))

Vectorized addition:
0.013392400000157068


In [36]:
def for_mul():
    return [item * 2 for item in my_list]

In [37]:
def vec_mul():
    return my_array * 2

In [38]:
print('For-loop multiplication:')
print(min(Timer(for_mul).repeat(10, 10)))

For-loop multiplication:
0.5338987999998608


In [39]:
print('Vectorized multiplication:')
print(min(Timer(vec_mul).repeat(10, 10)))

Vectorized multiplication:
0.013259199999993143


In [40]:
import math

In [41]:
def for_sqrt():
    return [math.sqrt(item) for item in my_list]

In [42]:
def vec_sqrt():
    return np.sqrt(my_array)

In [43]:
print('For-loop square root:')
print(min(Timer(for_sqrt).repeat(10, 10)))

For-loop square root:
1.069975599999907


In [44]:
print('Vectorized square root:')
print(min(Timer(vec_sqrt).repeat(10, 10)))

Vectorized square root:
0.01859199999989869


In [45]:
sample = np.random.normal()

In [46]:
sample

1.3647832318279887

In [47]:
sample = np.random.normal(loc=100, scale=10)

In [48]:
sample

92.64535417534441

In [49]:
samples = np.random.normal(loc=100, scale=10, size=(2,3))

In [50]:
samples

array([[ 99.90477874,  80.25088498, 100.42731846],
       [ 85.25410549,  94.80513858,  88.24399598]])

In [51]:
samples = np.random.poisson(lam=10, size = (2, 2))

In [52]:
samples

array([[12,  7],
       [ 9, 10]])

In [53]:
np.random.randint(low=0, high=10, size=(2,5))

array([[7, 4, 0, 0, 6],
       [2, 7, 1, 3, 7]])

In [54]:
np.random.choice([1,3,4,-6], size=(2,2))

array([[ 1, -6],
       [ 3,  1]])

In [55]:
a = [1, 2, 3, 4]

In [56]:
for _ in range(3):
    np.random.shuffle(a)
    print(a)

[3, 2, 1, 4]
[2, 3, 4, 1]
[1, 4, 3, 2]


In [57]:
import random
random.seed(0)

In [58]:
np.random.seed(0)

In [59]:
import pandas as pd

In [60]:
my_dict = {'col1': [1, 2], 'col2': np.array([3, 4]),'col3': [5, 6]}

In [61]:
df = pd.DataFrame(my_dict)

In [62]:
df

col1  col2  col3
0     1     3     5
1     2     4     6

In [63]:
my_array = np.array([[1, 3, 5], [2, 4, 6]])

In [64]:
alt_df = pd.DataFrame(my_array, columns=['col1', 'col2', 'col3'])

In [65]:
alt_df

col1  col2  col3
0     1     3     5
1     2     4     6