In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
b = np.array([1, 2, 'a'])

In [5]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
zero_array = np.zeros((2, 2))

In [8]:
zero_array

array([[0., 0.],
       [0., 0.]])

In [9]:
one_array = np.ones((2, 2, 3), dtype=int)

In [10]:
one_array

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [11]:
rand_array = np.random.rand(2, 3)

In [12]:
rand_array

array([[0.79128832, 0.78608187, 0.8045028 ],
       [0.31329908, 0.47357179, 0.19881362]])

In [13]:
a = np.array([1, 2, 3])

In [14]:
a[0]

1

In [15]:
a[1]

2

In [16]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [17]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
b[1, 1]

5

In [19]:
a = np.random.rand(2, 3, 4)

In [20]:
a

array([[[0.49454275, 0.61194539, 0.43676825, 0.53305104],
        [0.04877335, 0.29936532, 0.46371451, 0.08286806],
        [0.64903134, 0.00199007, 0.12693461, 0.44682895]],

       [[0.39491933, 0.96910371, 0.5716777 , 0.84111438],
        [0.81414391, 0.12565611, 0.27977221, 0.9121716 ],
        [0.56319667, 0.85878344, 0.7183086 , 0.80623853]]])

In [21]:
a[1, 0:2, 1:]

array([[0.96910371, 0.5716777 , 0.84111438],
       [0.12565611, 0.27977221, 0.9121716 ]])

In [22]:
a

array([[[0.49454275, 0.61194539, 0.43676825, 0.53305104],
        [0.04877335, 0.29936532, 0.46371451, 0.08286806],
        [0.64903134, 0.00199007, 0.12693461, 0.44682895]],

       [[0.39491933, 0.96910371, 0.5716777 , 0.84111438],
        [0.81414391, 0.12565611, 0.27977221, 0.9121716 ],
        [0.56319667, 0.85878344, 0.7183086 , 0.80623853]]])

In [23]:
a.shape

(2, 3, 4)

In [24]:
np.reshape(a, (3, 2, 4))

array([[[0.49454275, 0.61194539, 0.43676825, 0.53305104],
        [0.04877335, 0.29936532, 0.46371451, 0.08286806]],

       [[0.64903134, 0.00199007, 0.12693461, 0.44682895],
        [0.39491933, 0.96910371, 0.5716777 , 0.84111438]],

       [[0.81414391, 0.12565611, 0.27977221, 0.9121716 ],
        [0.56319667, 0.85878344, 0.7183086 , 0.80623853]]])

In [25]:
# np.reshape(a, (3, 3, 3))

In [26]:
a.T

array([[[0.49454275, 0.39491933],
        [0.04877335, 0.81414391],
        [0.64903134, 0.56319667]],

       [[0.61194539, 0.96910371],
        [0.29936532, 0.12565611],
        [0.00199007, 0.85878344]],

       [[0.43676825, 0.5716777 ],
        [0.46371451, 0.27977221],
        [0.12693461, 0.7183086 ]],

       [[0.53305104, 0.84111438],
        [0.08286806, 0.9121716 ],
        [0.44682895, 0.80623853]]])

In [27]:
import numpy as np

In [28]:
from timeit import Timer

In [29]:
my_list = list(range(10 ** 6))

In [30]:
my_array = np.array(my_list)

In [31]:
def for_add():
    return [item + 1 for item in my_list]

In [32]:
def vec_add():
    return my_array + 1

In [33]:
print('For-loop addition:')
print(min(Timer(for_add).repeat(10, 10)))

For-loop addition:
0.5140941999999953


In [34]:
print('Vectorized addition:')
print(min(Timer(vec_add).repeat(10, 10)))

Vectorized addition:
0.012109699999996337


In [35]:
def for_mul():
    return [item * 2 for item in my_list]

In [36]:
def vec_mul():
    return my_array * 2

In [37]:
print('For-loop multiplication:')
print(min(Timer(for_mul).repeat(10, 10)))

For-loop multiplication:
0.5369924000000026


In [38]:
print('Vectorized multiplication:')
print(min(Timer(vec_mul).repeat(10, 10)))

Vectorized multiplication:
0.012874000000003605


In [39]:
import math

In [40]:
def for_sqrt():
    return [math.sqrt(item) for item in my_list]

In [41]:
def vec_sqrt():
    return np.sqrt(my_array)

In [42]:
print('For-loop square root:')
print(min(Timer(for_sqrt).repeat(10, 10)))

For-loop square root:
1.1488602000000014


In [43]:
print('Vectorized square root:')
print(min(Timer(vec_sqrt).repeat(10, 10)))

Vectorized square root:
0.017188199999999654


In [44]:
sample = np.random.normal()

In [45]:
sample

-1.4859846859526906

In [46]:
sample = np.random.normal(loc=100, scale=10)

In [47]:
sample

105.00557991323986

In [48]:
samples = np.random.normal(loc=100, scale=10, size=(2,3))

In [49]:
samples

array([[110.10051048,  93.18510106,  94.57640426],
       [ 88.73162673,  92.40605742, 119.32473314]])

In [50]:
samples = np.random.poisson(lam=10, size = (2, 2))

In [51]:
samples

array([[ 6,  6],
       [10, 14]])

In [52]:
np.random.randint(low=0, high=10, size=(2,5))

array([[6, 8, 1, 2, 7],
       [0, 2, 1, 7, 5]])

In [53]:
np.random.choice([1,3,4,-6], size=(2,2))

array([[-6,  3],
       [ 1, -6]])

In [54]:
a = [1, 2, 3, 4]

In [55]:
for _ in range(3):
    np.random.shuffle(a)
    print(a)

[1, 2, 3, 4]
[1, 4, 3, 2]
[1, 2, 4, 3]


In [56]:
import random
random.seed(0)

In [57]:
np.random.seed(0)

In [58]:
import pandas as pd

In [59]:
my_dict = {'col1': [1, 2], 'col2': np.array([3, 4]),'col3': [5, 6]}

In [60]:
df = pd.DataFrame(my_dict)

In [61]:
df

col1  col2  col3
0     1     3     5
1     2     4     6

In [62]:
my_array = np.array([[1, 3, 5], [2, 4, 6]])

In [63]:
alt_df = pd.DataFrame(my_array, columns=['col1', 'col2', 'col3'])

In [64]:
alt_df

col1  col2  col3
0     1     3     5
1     2     4     6

In [65]:
df.loc[0]

col1    1
col2    3
col3    5
Name: 0, dtype: int64

In [66]:
df.loc[[0, 1]]

col1  col2  col3
0     1     3     5
1     2     4     6

In [67]:
df.loc[0, ['col2', 'col3']]

col2    3
col3    5
Name: 0, dtype: int64

In [68]:
df['col3']

0    5
1    6
Name: col3, dtype: int64

In [69]:
for item in df.loc[:, 'col3']:
    print(item)

5
6


In [70]:
df.loc[0] = [3, 6, 9]

In [71]:
df

col1  col2  col3
0     3     6     9
1     2     4     6

In [72]:
df['col2'] = [0, 0]

In [73]:
df['col4'] = [10, 10]

In [74]:
df.loc[3] = [1, 2, 3, 4]

In [75]:
df

col1  col2  col3  col4
0     3     0     9    10
1     2     0     6    10
3     1     2     3     4

In [76]:
df.loc[[False, True, False], [False, True, False, True]]

col2  col4
1     0    10

In [77]:
df.loc[:, df.loc[0] > 5]

col3  col4
0     9    10
1     6    10
3     3     4